[tool.poetry]
name = "data-join-tabular"
version = "0.1.0"
description = ""
authors = ["NourKired <n.kired@okp4.com>"]

[tool.poetry.dependencies]
python = "^3.9"
geopandas = "^0.11.0"
tqdm = "^4.64.0"
flake8 = "^4.0.1"
pytest = "^7.1.2"

[tool.poetry.scripts]
data-join-tabular = "data_join_tabular.main:cli"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
